// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Conversation struct {
	ID        int32
	Name      string
	CreatedAt sql.NullTime
}

type ConversationParticipant struct {
	ConversationID int32
	UserID         int32
}

type Message struct {
	ID             int32
	ConversationID int32
	SenderID       int32
	Body           string
	CreatedAt      sql.NullTime
}

type User struct {
	ID           int32
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
}
